#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
ip=$3
port=$4
app=htpc

sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# Copy of app for localhost installation
if [[ $ip == "127.0.0.1" ]]; then
  sudo apt-get install libjpeg libjpeg-dev libpng-dev libfreetype6 libfreetype6-dev zlib1g-dev -y
  sudo apt-get install python-pip -y
  sudo pip install PIL
  final_path=/opt/$app
  sudo mkdir -p $final_path
  sudo cp -a ../sources/* $final_path
  sudo cp -a ../conf/$app /etc/init.d/
  sudo chmod +x /etc/init.d/$app
  sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/init.d/$app
  sudo update-rc.d /etc/init.d/$app defaults
  sudo service $app start
fi

# Configure Nginx and reload
sudo sed -i "s@IPTOCHANGE@$ip@g" ../conf/nginx.conf
sudo sed -i "s@PORT@$port@g" ../conf/nginx.conf
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
sudo service nginx reload
