#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
ip=$3
port=$4
app=htpc

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check port availability
sudo yunohost app checkport $port
if [[ ! $? -eq 0 ]]; then
      exit 1
  fi
  
# Copy of app for localhost installation
if [[ $ip == "127.0.0.1" ]]; then
	sudo apt-get install libjpeg libjpeg-dev libpng-dev libfreetype6 libfreetype6-dev zlib1g-dev -y
	sudo apt-get install python-pip -y
	sudo pip install PIL
	
	#Install the latest version of HTPC-Manager using the fork
	sudo mkdir -p /opt/yunohost/$app
	sudo git clone https://github.com/styxit/HTPC-Manager /opt/yunohost/$app
	
	sudo cp -a ../conf/$app /etc/init.d/
	sudo chmod +x /etc/init.d/$app
	sudo sed -i "s@PATHTOCHANGE@$path@g" /etc/init.d/$app
	sudo sed -i "s@PORT@$port@g" /etc/init.d/$app
fi

# Configure Nginx 
sudo sed -i "s@IPTOCHANGE@$ip@g" ../conf/nginx.conf
sudo sed -i "s@PORT@$port@g" ../conf/nginx.conf
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Add GateOne service to YunoHost's monitoring
sudo yunohost service add $app --log /var/log/$app/ --status "ps aux | grep $app | grep -v grep"


# Start $app service at boot
sudo update-rc.d $app defaults

# Reload $app, Nginx and regenerate SSOwat conf
sudo service $app restart
sudo service nginx reload
sudo yunohost app ssowatconf